disabled_rules:
    - line_length
    - trailing_whitespace
opt_in_rules: # some rules are only opt-in
    - control_statement
    - trailing_newline
    - colon
    - overridden_super_call
    - comma

included:
    - IRShowcase
excluded:
    - Carthage
    - IRShowcaseTests
reporter: "xcode"

force_cast: warning

nesting:
    type_level:
        warning: 2
    statement_level:
        warning: 5

large_tuple:
    - 3
    - 6

type_body_length:
    - 300
    - 500

cyclomatic_complexity:
    - 30
    - 60

identifier_name: 
    min_length: 
        warning: 1
        error: 0

type_name:
    excluded:
    - "T"
    - "I"
    - "V"
    - "E"

